CREATE DATABASE hotel_db;

CREATE TABLE RESERVATION (
	RESERVATION_ID SERIAL PRIMARY KEY,
	GUEST_NAME VARCHAR(100),
	ROOM_NUMBER INT,
	CONTACT_NUMBER VARCHAR(12),
	RESERVATION_DATE TIMESTAMP DEFAULT CURRENT_TIME
);

SELECT * FROM RESERVATION;